[package]
name = "ropship-inspired-lang"
version = "0.1.0"
authors = ["Avi Weinstock <aweinstock314@gmail.com>"]
edition = "2018"

[dependencies]
goblin = "0.2"
pest = "2.1"
pest_derive = "2.1"
petgraph = "0.5"
lazy_static = "1.4.0"

[features]
also_check_raw_gadgets = []
